

SELECT 'Rentals: PID --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Rentals
    GROUP BY PID
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Rentals: PID --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Rentals
    GROUP BY PID
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Rentals: PID --> S' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Rentals
    GROUP BY PID
    HAVING COUNT(DISTINCT S) > 1
) X;


SELECT 'Rentals: PID --> HS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Rentals
    GROUP BY PID
    HAVING COUNT(DISTINCT HS) > 1
) X;


SELECT 'Rentals: PID --> HZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Rentals
    GROUP BY PID
    HAVING COUNT(DISTINCT HZ) > 1
) X;


SELECT 'Rentals: PID --> HC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Rentals
    GROUP BY PID
    HAVING COUNT(DISTINCT HC) > 1
) X;


SELECT 'Rentals: HID --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Rentals
    GROUP BY HID
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Rentals: HID --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Rentals
    GROUP BY HID
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Rentals: HID --> S' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Rentals
    GROUP BY HID
    HAVING COUNT(DISTINCT S) > 1
) X;


SELECT 'Rentals: HID --> HS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Rentals
    GROUP BY HID
    HAVING COUNT(DISTINCT HS) > 1
) X;


SELECT 'Rentals: HID --> HZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Rentals
    GROUP BY HID
    HAVING COUNT(DISTINCT HZ) > 1
) X;


SELECT 'Rentals: HID --> HC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Rentals
    GROUP BY HID
    HAVING COUNT(DISTINCT HC) > 1
) X;


SELECT 'Rentals: PN --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Rentals
    GROUP BY PN
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Rentals: PN --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Rentals
    GROUP BY PN
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Rentals: PN --> S' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Rentals
    GROUP BY PN
    HAVING COUNT(DISTINCT S) > 1
) X;


SELECT 'Rentals: PN --> HS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Rentals
    GROUP BY PN
    HAVING COUNT(DISTINCT HS) > 1
) X;


SELECT 'Rentals: PN --> HZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Rentals
    GROUP BY PN
    HAVING COUNT(DISTINCT HZ) > 1
) X;


SELECT 'Rentals: PN --> HC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Rentals
    GROUP BY PN
    HAVING COUNT(DISTINCT HC) > 1
) X;


SELECT 'Rentals: S --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT S
    FROM Rentals
    GROUP BY S
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Rentals: S --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT S
    FROM Rentals
    GROUP BY S
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Rentals: S --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT S
    FROM Rentals
    GROUP BY S
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Rentals: S --> HS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT S
    FROM Rentals
    GROUP BY S
    HAVING COUNT(DISTINCT HS) > 1
) X;


SELECT 'Rentals: S --> HZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT S
    FROM Rentals
    GROUP BY S
    HAVING COUNT(DISTINCT HZ) > 1
) X;


SELECT 'Rentals: S --> HC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT S
    FROM Rentals
    GROUP BY S
    HAVING COUNT(DISTINCT HC) > 1
) X;


SELECT 'Rentals: HS --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HS
    FROM Rentals
    GROUP BY HS
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Rentals: HS --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HS
    FROM Rentals
    GROUP BY HS
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Rentals: HS --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HS
    FROM Rentals
    GROUP BY HS
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Rentals: HS --> S' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HS
    FROM Rentals
    GROUP BY HS
    HAVING COUNT(DISTINCT S) > 1
) X;


SELECT 'Rentals: HS --> HZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HS
    FROM Rentals
    GROUP BY HS
    HAVING COUNT(DISTINCT HZ) > 1
) X;


SELECT 'Rentals: HS --> HC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HS
    FROM Rentals
    GROUP BY HS
    HAVING COUNT(DISTINCT HC) > 1
) X;


SELECT 'Rentals: HZ --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HZ
    FROM Rentals
    GROUP BY HZ
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Rentals: HZ --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HZ
    FROM Rentals
    GROUP BY HZ
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Rentals: HZ --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HZ
    FROM Rentals
    GROUP BY HZ
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Rentals: HZ --> S' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HZ
    FROM Rentals
    GROUP BY HZ
    HAVING COUNT(DISTINCT S) > 1
) X;


SELECT 'Rentals: HZ --> HS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HZ
    FROM Rentals
    GROUP BY HZ
    HAVING COUNT(DISTINCT HS) > 1
) X;


SELECT 'Rentals: HZ --> HC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HZ
    FROM Rentals
    GROUP BY HZ
    HAVING COUNT(DISTINCT HC) > 1
) X;


SELECT 'Rentals: HC --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HC
    FROM Rentals
    GROUP BY HC
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Rentals: HC --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HC
    FROM Rentals
    GROUP BY HC
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Rentals: HC --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HC
    FROM Rentals
    GROUP BY HC
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Rentals: HC --> S' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HC
    FROM Rentals
    GROUP BY HC
    HAVING COUNT(DISTINCT S) > 1
) X;


SELECT 'Rentals: HC --> HS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HC
    FROM Rentals
    GROUP BY HC
    HAVING COUNT(DISTINCT HS) > 1
) X;


SELECT 'Rentals: HC --> HZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HC
    FROM Rentals
    GROUP BY HC
    HAVING COUNT(DISTINCT HZ) > 1
) X;


SELECT 'Coffees: DID --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DID
    FROM Coffees
    GROUP BY DID
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Coffees: DID --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DID
    FROM Coffees
    GROUP BY DID
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Coffees: DID --> DN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DID
    FROM Coffees
    GROUP BY DID
    HAVING COUNT(DISTINCT DN) > 1
) X;


SELECT 'Coffees: DID --> DS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DID
    FROM Coffees
    GROUP BY DID
    HAVING COUNT(DISTINCT DS) > 1
) X;


SELECT 'Coffees: DID --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DID
    FROM Coffees
    GROUP BY DID
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Coffees: DID --> CM' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DID
    FROM Coffees
    GROUP BY DID
    HAVING COUNT(DISTINCT CM) > 1
) X;


SELECT 'Coffees: HID --> DID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Coffees
    GROUP BY HID
    HAVING COUNT(DISTINCT DID) > 1
) X;


SELECT 'Coffees: HID --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Coffees
    GROUP BY HID
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Coffees: HID --> DN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Coffees
    GROUP BY HID
    HAVING COUNT(DISTINCT DN) > 1
) X;


SELECT 'Coffees: HID --> DS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Coffees
    GROUP BY HID
    HAVING COUNT(DISTINCT DS) > 1
) X;


SELECT 'Coffees: HID --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Coffees
    GROUP BY HID
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Coffees: HID --> CM' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT HID
    FROM Coffees
    GROUP BY HID
    HAVING COUNT(DISTINCT CM) > 1
) X;


SELECT 'Coffees: CID --> DID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Coffees
    GROUP BY CID
    HAVING COUNT(DISTINCT DID) > 1
) X;


SELECT 'Coffees: CID --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Coffees
    GROUP BY CID
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Coffees: CID --> DN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Coffees
    GROUP BY CID
    HAVING COUNT(DISTINCT DN) > 1
) X;


SELECT 'Coffees: CID --> DS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Coffees
    GROUP BY CID
    HAVING COUNT(DISTINCT DS) > 1
) X;


SELECT 'Coffees: CID --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Coffees
    GROUP BY CID
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Coffees: CID --> CM' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Coffees
    GROUP BY CID
    HAVING COUNT(DISTINCT CM) > 1
) X;


SELECT 'Coffees: DN --> DID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DN
    FROM Coffees
    GROUP BY DN
    HAVING COUNT(DISTINCT DID) > 1
) X;


SELECT 'Coffees: DN --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DN
    FROM Coffees
    GROUP BY DN
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Coffees: DN --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DN
    FROM Coffees
    GROUP BY DN
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Coffees: DN --> DS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DN
    FROM Coffees
    GROUP BY DN
    HAVING COUNT(DISTINCT DS) > 1
) X;


SELECT 'Coffees: DN --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DN
    FROM Coffees
    GROUP BY DN
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Coffees: DN --> CM' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DN
    FROM Coffees
    GROUP BY DN
    HAVING COUNT(DISTINCT CM) > 1
) X;


SELECT 'Coffees: DS --> DID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DS
    FROM Coffees
    GROUP BY DS
    HAVING COUNT(DISTINCT DID) > 1
) X;


SELECT 'Coffees: DS --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DS
    FROM Coffees
    GROUP BY DS
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Coffees: DS --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DS
    FROM Coffees
    GROUP BY DS
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Coffees: DS --> DN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DS
    FROM Coffees
    GROUP BY DS
    HAVING COUNT(DISTINCT DN) > 1
) X;


SELECT 'Coffees: DS --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DS
    FROM Coffees
    GROUP BY DS
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Coffees: DS --> CM' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT DS
    FROM Coffees
    GROUP BY DS
    HAVING COUNT(DISTINCT CM) > 1
) X;


SELECT 'Coffees: CN --> DID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Coffees
    GROUP BY CN
    HAVING COUNT(DISTINCT DID) > 1
) X;


SELECT 'Coffees: CN --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Coffees
    GROUP BY CN
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Coffees: CN --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Coffees
    GROUP BY CN
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Coffees: CN --> DN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Coffees
    GROUP BY CN
    HAVING COUNT(DISTINCT DN) > 1
) X;


SELECT 'Coffees: CN --> DS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Coffees
    GROUP BY CN
    HAVING COUNT(DISTINCT DS) > 1
) X;


SELECT 'Coffees: CN --> CM' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Coffees
    GROUP BY CN
    HAVING COUNT(DISTINCT CM) > 1
) X;


SELECT 'Coffees: CM --> DID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CM
    FROM Coffees
    GROUP BY CM
    HAVING COUNT(DISTINCT DID) > 1
) X;


SELECT 'Coffees: CM --> HID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CM
    FROM Coffees
    GROUP BY CM
    HAVING COUNT(DISTINCT HID) > 1
) X;


SELECT 'Coffees: CM --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CM
    FROM Coffees
    GROUP BY CM
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Coffees: CM --> DN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CM
    FROM Coffees
    GROUP BY CM
    HAVING COUNT(DISTINCT DN) > 1
) X;


SELECT 'Coffees: CM --> DS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CM
    FROM Coffees
    GROUP BY CM
    HAVING COUNT(DISTINCT DS) > 1
) X;


SELECT 'Coffees: CM --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CM
    FROM Coffees
    GROUP BY CM
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Projects: ID --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT ID
    FROM Projects
    GROUP BY ID
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Projects: ID --> SID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT ID
    FROM Projects
    GROUP BY ID
    HAVING COUNT(DISTINCT SID) > 1
) X;


SELECT 'Projects: ID --> SN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT ID
    FROM Projects
    GROUP BY ID
    HAVING COUNT(DISTINCT SN) > 1
) X;


SELECT 'Projects: ID --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT ID
    FROM Projects
    GROUP BY ID
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Projects: ID --> MID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT ID
    FROM Projects
    GROUP BY ID
    HAVING COUNT(DISTINCT MID) > 1
) X;


SELECT 'Projects: ID --> MN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT ID
    FROM Projects
    GROUP BY ID
    HAVING COUNT(DISTINCT MN) > 1
) X;


SELECT 'Projects: PID --> ID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Projects
    GROUP BY PID
    HAVING COUNT(DISTINCT ID) > 1
) X;


SELECT 'Projects: PID --> SID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Projects
    GROUP BY PID
    HAVING COUNT(DISTINCT SID) > 1
) X;


SELECT 'Projects: PID --> SN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Projects
    GROUP BY PID
    HAVING COUNT(DISTINCT SN) > 1
) X;


SELECT 'Projects: PID --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Projects
    GROUP BY PID
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Projects: PID --> MID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Projects
    GROUP BY PID
    HAVING COUNT(DISTINCT MID) > 1
) X;


SELECT 'Projects: PID --> MN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PID
    FROM Projects
    GROUP BY PID
    HAVING COUNT(DISTINCT MN) > 1
) X;


SELECT 'Projects: SID --> ID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SID
    FROM Projects
    GROUP BY SID
    HAVING COUNT(DISTINCT ID) > 1
) X;


SELECT 'Projects: SID --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SID
    FROM Projects
    GROUP BY SID
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Projects: SID --> SN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SID
    FROM Projects
    GROUP BY SID
    HAVING COUNT(DISTINCT SN) > 1
) X;


SELECT 'Projects: SID --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SID
    FROM Projects
    GROUP BY SID
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Projects: SID --> MID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SID
    FROM Projects
    GROUP BY SID
    HAVING COUNT(DISTINCT MID) > 1
) X;


SELECT 'Projects: SID --> MN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SID
    FROM Projects
    GROUP BY SID
    HAVING COUNT(DISTINCT MN) > 1
) X;


SELECT 'Projects: SN --> ID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SN
    FROM Projects
    GROUP BY SN
    HAVING COUNT(DISTINCT ID) > 1
) X;


SELECT 'Projects: SN --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SN
    FROM Projects
    GROUP BY SN
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Projects: SN --> SID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SN
    FROM Projects
    GROUP BY SN
    HAVING COUNT(DISTINCT SID) > 1
) X;


SELECT 'Projects: SN --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SN
    FROM Projects
    GROUP BY SN
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Projects: SN --> MID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SN
    FROM Projects
    GROUP BY SN
    HAVING COUNT(DISTINCT MID) > 1
) X;


SELECT 'Projects: SN --> MN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT SN
    FROM Projects
    GROUP BY SN
    HAVING COUNT(DISTINCT MN) > 1
) X;


SELECT 'Projects: PN --> ID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Projects
    GROUP BY PN
    HAVING COUNT(DISTINCT ID) > 1
) X;


SELECT 'Projects: PN --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Projects
    GROUP BY PN
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Projects: PN --> SID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Projects
    GROUP BY PN
    HAVING COUNT(DISTINCT SID) > 1
) X;


SELECT 'Projects: PN --> SN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Projects
    GROUP BY PN
    HAVING COUNT(DISTINCT SN) > 1
) X;


SELECT 'Projects: PN --> MID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Projects
    GROUP BY PN
    HAVING COUNT(DISTINCT MID) > 1
) X;


SELECT 'Projects: PN --> MN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT PN
    FROM Projects
    GROUP BY PN
    HAVING COUNT(DISTINCT MN) > 1
) X;


SELECT 'Projects: MID --> ID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MID
    FROM Projects
    GROUP BY MID
    HAVING COUNT(DISTINCT ID) > 1
) X;


SELECT 'Projects: MID --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MID
    FROM Projects
    GROUP BY MID
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Projects: MID --> SID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MID
    FROM Projects
    GROUP BY MID
    HAVING COUNT(DISTINCT SID) > 1
) X;


SELECT 'Projects: MID --> SN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MID
    FROM Projects
    GROUP BY MID
    HAVING COUNT(DISTINCT SN) > 1
) X;


SELECT 'Projects: MID --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MID
    FROM Projects
    GROUP BY MID
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Projects: MID --> MN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MID
    FROM Projects
    GROUP BY MID
    HAVING COUNT(DISTINCT MN) > 1
) X;


SELECT 'Projects: MN --> ID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MN
    FROM Projects
    GROUP BY MN
    HAVING COUNT(DISTINCT ID) > 1
) X;


SELECT 'Projects: MN --> PID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MN
    FROM Projects
    GROUP BY MN
    HAVING COUNT(DISTINCT PID) > 1
) X;


SELECT 'Projects: MN --> SID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MN
    FROM Projects
    GROUP BY MN
    HAVING COUNT(DISTINCT SID) > 1
) X;


SELECT 'Projects: MN --> SN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MN
    FROM Projects
    GROUP BY MN
    HAVING COUNT(DISTINCT SN) > 1
) X;


SELECT 'Projects: MN --> PN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MN
    FROM Projects
    GROUP BY MN
    HAVING COUNT(DISTINCT PN) > 1
) X;


SELECT 'Projects: MN --> MID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT MN
    FROM Projects
    GROUP BY MN
    HAVING COUNT(DISTINCT MID) > 1
) X;


SELECT 'Customers: CID --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Customers
    GROUP BY CID
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Customers: CID --> CS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Customers
    GROUP BY CID
    HAVING COUNT(DISTINCT CS) > 1
) X;


SELECT 'Customers: CID --> CNr' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Customers
    GROUP BY CID
    HAVING COUNT(DISTINCT CNr) > 1
) X;


SELECT 'Customers: CID --> CZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Customers
    GROUP BY CID
    HAVING COUNT(DISTINCT CZ) > 1
) X;


SELECT 'Customers: CID --> CC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Customers
    GROUP BY CID
    HAVING COUNT(DISTINCT CC) > 1
) X;


SELECT 'Customers: CID --> EID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CID
    FROM Customers
    GROUP BY CID
    HAVING COUNT(DISTINCT EID) > 1
) X;


SELECT 'Customers: CN --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Customers
    GROUP BY CN
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Customers: CN --> CS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Customers
    GROUP BY CN
    HAVING COUNT(DISTINCT CS) > 1
) X;


SELECT 'Customers: CN --> CNr' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Customers
    GROUP BY CN
    HAVING COUNT(DISTINCT CNr) > 1
) X;


SELECT 'Customers: CN --> CZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Customers
    GROUP BY CN
    HAVING COUNT(DISTINCT CZ) > 1
) X;


SELECT 'Customers: CN --> CC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Customers
    GROUP BY CN
    HAVING COUNT(DISTINCT CC) > 1
) X;


SELECT 'Customers: CN --> EID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CN
    FROM Customers
    GROUP BY CN
    HAVING COUNT(DISTINCT EID) > 1
) X;


SELECT 'Customers: CS --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CS
    FROM Customers
    GROUP BY CS
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Customers: CS --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CS
    FROM Customers
    GROUP BY CS
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Customers: CS --> CNr' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CS
    FROM Customers
    GROUP BY CS
    HAVING COUNT(DISTINCT CNr) > 1
) X;


SELECT 'Customers: CS --> CZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CS
    FROM Customers
    GROUP BY CS
    HAVING COUNT(DISTINCT CZ) > 1
) X;


SELECT 'Customers: CS --> CC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CS
    FROM Customers
    GROUP BY CS
    HAVING COUNT(DISTINCT CC) > 1
) X;


SELECT 'Customers: CS --> EID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CS
    FROM Customers
    GROUP BY CS
    HAVING COUNT(DISTINCT EID) > 1
) X;


SELECT 'Customers: CNr --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CNr
    FROM Customers
    GROUP BY CNr
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Customers: CNr --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CNr
    FROM Customers
    GROUP BY CNr
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Customers: CNr --> CS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CNr
    FROM Customers
    GROUP BY CNr
    HAVING COUNT(DISTINCT CS) > 1
) X;


SELECT 'Customers: CNr --> CZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CNr
    FROM Customers
    GROUP BY CNr
    HAVING COUNT(DISTINCT CZ) > 1
) X;


SELECT 'Customers: CNr --> CC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CNr
    FROM Customers
    GROUP BY CNr
    HAVING COUNT(DISTINCT CC) > 1
) X;


SELECT 'Customers: CNr --> EID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CNr
    FROM Customers
    GROUP BY CNr
    HAVING COUNT(DISTINCT EID) > 1
) X;


SELECT 'Customers: CZ --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CZ
    FROM Customers
    GROUP BY CZ
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Customers: CZ --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CZ
    FROM Customers
    GROUP BY CZ
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Customers: CZ --> CS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CZ
    FROM Customers
    GROUP BY CZ
    HAVING COUNT(DISTINCT CS) > 1
) X;


SELECT 'Customers: CZ --> CNr' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CZ
    FROM Customers
    GROUP BY CZ
    HAVING COUNT(DISTINCT CNr) > 1
) X;


SELECT 'Customers: CZ --> CC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CZ
    FROM Customers
    GROUP BY CZ
    HAVING COUNT(DISTINCT CC) > 1
) X;


SELECT 'Customers: CZ --> EID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CZ
    FROM Customers
    GROUP BY CZ
    HAVING COUNT(DISTINCT EID) > 1
) X;


SELECT 'Customers: CC --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CC
    FROM Customers
    GROUP BY CC
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Customers: CC --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CC
    FROM Customers
    GROUP BY CC
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Customers: CC --> CS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CC
    FROM Customers
    GROUP BY CC
    HAVING COUNT(DISTINCT CS) > 1
) X;


SELECT 'Customers: CC --> CNr' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CC
    FROM Customers
    GROUP BY CC
    HAVING COUNT(DISTINCT CNr) > 1
) X;


SELECT 'Customers: CC --> CZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CC
    FROM Customers
    GROUP BY CC
    HAVING COUNT(DISTINCT CZ) > 1
) X;


SELECT 'Customers: CC --> EID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT CC
    FROM Customers
    GROUP BY CC
    HAVING COUNT(DISTINCT EID) > 1
) X;


SELECT 'Customers: EID --> CID' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT EID
    FROM Customers
    GROUP BY EID
    HAVING COUNT(DISTINCT CID) > 1
) X;


SELECT 'Customers: EID --> CN' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT EID
    FROM Customers
    GROUP BY EID
    HAVING COUNT(DISTINCT CN) > 1
) X;


SELECT 'Customers: EID --> CS' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT EID
    FROM Customers
    GROUP BY EID
    HAVING COUNT(DISTINCT CS) > 1
) X;


SELECT 'Customers: EID --> CNr' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT EID
    FROM Customers
    GROUP BY EID
    HAVING COUNT(DISTINCT CNr) > 1
) X;


SELECT 'Customers: EID --> CZ' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT EID
    FROM Customers
    GROUP BY EID
    HAVING COUNT(DISTINCT CZ) > 1
) X;


SELECT 'Customers: EID --> CC' AS FD,
    CASE WHEN COUNT(*) = 0 THEN
        'HOLDS'
    END AS VALIDITY
FROM (
    SELECT EID
    FROM Customers
    GROUP BY EID
    HAVING COUNT(DISTINCT CC) > 1
) X;
